CREATE TABLE IF NOT EXISTS lockers (
    id SERIAL PRIMARY KEY,
    locker_number INTEGER NOT NULL UNIQUE,
    is_used BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
